# CI / CD of pr0ton11 builds

name: 'Build from upstream'

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v4
      - name: "Build:dockerlogin"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/pr0ton11/piped-frontend:latest
